import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/app/auth/Provider";
import Navbar from "./components/header/Navbar";
import TanstackProvider from "./providers/TanstackProvider";
import ToastProvider from "./providers/ToastProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
  
}>,) {
  return (
    <html lang="en">
    <body className={inter.className}>
      <ToastProvider> {/* Wrap your app with ToastProvider */}
        <TanstackProvider>
          <AuthProvider>
            <Navbar />
            {children}
          </AuthProvider>
        </TanstackProvider>
      </ToastProvider>
    </body>
  </html>
  );
}
